baseURL: https://kozin.cc/
languageCode: en-us
title: Stanislav Kozin's Webpage
theme: kozin

defaultContentLanguage: en

Languages:
  en:
    contentDir: content/eng
    weight: 0
    languagename: ğŸ‡ºğŸ‡¸
    title: Stanislav Kozin' Homepage
    menu:
        main:
          - url: /
            name: Home
            weight: 0
          - url: /about/
            name: About
            weight: 1


  ru:
    contentDir: content/rus
    weight: 1
    languagename: ğŸ‡·ğŸ‡º
    title: Ğ¡Ñ‚Ğ°Ğ½Ğ¸ÑĞ»Ğ°Ğ² ĞšĞ¾Ğ·Ğ¸Ğ½
    menu:
      main:
        - url: /
          name: Ğ”Ğ¾Ğ¼Ğ¾Ğ¹
          weight: 0
        - url: /about/
          name: ĞĞ±Ğ¾ ĞœĞ½Ğµ
          weight: 1